### ISSUE TITLE
How to get all the sharp images for each blur image using render.py?

### ISSUE THREAD

**Issue by GopiRajuMatta** [Chaphlagical/Deblur-GS#21]
Hello @Chaphlagical!

Can you please help me to get all the sharp images rendered for each blurry image.. Please suggest me where to make changes in render.py

Thank you
Gopi

**Comment by Chaphlagical** [comment]
You use the same camera poses of the blurry images as `views` in https://github.com/Chaphlagical/Deblur-GS/blob/3b80ea851899f2dc6a24a63cff4f6f2e6c94b856/render.py#L60
And you will get the sharp images corresponding to the blurry images.

**Comment by GopiRajuMatta** [comment]
Thank you for your reply.. 

What I meant is, let's say if blur_sample_num=31, we are getting 31 sharp images, so I want to render those 31 sharp images for each blurry image.

Thank you
Gopi

**Comment by Chaphlagical** [comment]
Oh, the 31 sharp images came from camera trajectory interpolation, so you may have to do the curve interpolation like the training process
