### ISSUE TITLE
Pre-trained models

### ISSUE THREAD

**Issue by TDNAI** [Chaphlagical/Deblur-GS#3]
Hello and thank you in advance for sharing this amazing work.
I would like to test some custom images and videos using some pretrained models, but 
I did not find any links to any pretrained weights. 
Are you willing to share your pretrained models publicly?

**Comment by Chaphlagical** [comment]
Well, our method is essentially a 3D reconstruction algorithm from blurred multi-view images. Therefore, it might not be like other deep learning deblurring method as you think. The pretrain model can only present the reconstructed scene of the input images and you have to retrain for the custom dataset.
