### ISSUE TITLE
Not being able to reproduce the paper quality

### ISSUE THREAD

**Issue by pdxmusic** [Chaphlagical/Deblur-GS#5]
tonight I ran a training session using this command:

`python train.py -s /deblur-datasets/bench/ --eval --deblur`

This is the final output:
`[ITER 89000] Evaluating train: L1 0.07883617728948594 PSNR 18.672360610961913 SSIM 0.5059403717517853 LPIPS 0.5323960781097412 [17/05 02:12:15]`

This is how long it took
`Training progress: 100%|█| 90000/90000 [6:58:09<00:00,  3.59it/s, Loss=0.0423791`

This is the ply result
<img width="1437" alt="result" src="https://github.com/Chaphlagical/Deblur-GS/assets/2960367/ccc20046-8b57-4e5d-9892-9dd8ee3aa5e1">

Is there something I'm missing? 
Is it possible to know which parameters were used in the training results of the paper?

Thanks in advance!

**Comment by Chaphlagical** [comment]
I might change the order of the quaternion vector of the original 3dgs framework. Therefore, SIBR viewer might not works well. How about the result from `render.py` or `render_video.py`? Maybe I will change the order back when I have some free time. Sorry for the inconvenience.

**Comment by pdxmusic** [comment]
The video render is perfect!

**Comment by mhb0928** [comment]
![000](https://github.com/user-attachments/assets/0a30faab-5bcb-485c-9e3a-f74eaa72c25e)
我跑的结果bench 第一张
