### ISSUE TITLE
How to prepare custom data and train without sharp GT images?

### ISSUE THREAD

**Issue by KaqiKaqi** [Chaphlagical/Deblur-GS#8]
My question is exactly the title.

**Comment by Chaphlagical** [comment]
You can follow the original 3D Gaussian Splatting project [https://github.com/graphdeco-inria/gaussian-splatting](https://github.com/graphdeco-inria/gaussian-splatting) to prepare custom data. If you don't have sharp GT images, it may come across some path issue in ths project. You can fix it by copy the `images` folder and rename as `image_test`.
